config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'

  resources :gnomes do
    collection do
      get :my_gnomes
    end
    resources :bookings, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:new, :create, :index]

    resources :bookings do
      member do
        patch '/validate', to: 'bookings#validate'
      end

    end
    resources :review, only: [:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :gnome

  validates :user_id, :gnome_id, :date_start, :date_end, :price_total, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :gnome
end

app/models/gnome.rb
class Gnome < ApplicationRecord

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :bookings
  has_many :reviews, dependent: :destroy
  CATEGORY = %w[Authentique Zombie Bdsm Familial Potache Zen Groupé Mignon Connu]
  COLOR = %w[Rouge Vert Blanc Jaune Orange Bleu Noir]
  MOOD = %w[Joyeux Triste Colérique Détendu]

  validates :name, :price, :photo, presence: true
  validates :category, inclusion: { in: CATEGORY }
  validates :color, inclusion: { in: COLOR }
  validates :mood, inclusion: { in: MOOD }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :gnome, dependent: :destroy
  belongs_to :user, dependent: :destroy
  validates :comment, :rating, presence:true
  validates :rating, inclusion: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gnomes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookings
  has_many :reviews
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = booking.all
    authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])
    @gnome = Gnome.find(params[:gnome_id])
    authorize @booking
  end

  def new
    authorize @booking
    @gnome = Gnome.find(params[:gnome_id])
    @booking = Booking.new
  end

  def create
    @gnome = Gnome.find(params[:gnome_id])
    @booking = Booking.new(booking_params)
    @booking.gnome = @gnome
    @booking.user = current_user
    @number_days = (@booking.date_end - @booking.date_start).to_i + 1
    @booking.price_total= @number_days * @gnome.price
    authorize @booking
    if @booking.save
      redirect_to  gnome_booking_path(@gnome, @booking)
    else
      redirect_to  gnome_booking_path(@gnome, @booking)
    end
  end

  def validate
    @booking = Booking.find(params[:id])
    @booking.update(validated: true)
    flash[:notice] = 'Votre réservation a bien été validée.'
    skip_authorization
    redirect_to dashboard_path
  end

  def destroy
    @booking = booking.find(params[:id])
    @gnome = @booking.gnome
    authorize @booking
    @booking.destroy
    redirect_to gnome_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit( :date_start, :date_end, :gnome_id, :user_id )
  end

end

app/controllers/gnomes_controller.rb
class GnomesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
  #  @gnomes = policy_scope(Gnome)
  #  if params.dig(:search, :category)
  #    if params.dig(:search, :category) == ""
  #      if params.dig(:search, :color) == ""
  #        @gnomes = Gnome.all
  #      else
  #        @gnomes = @gnomes.where(color: params.dig(:search, :color))
  #      end
  #    else
  #      if params.dig(:search, :color) == ""
  #        @gnomes = @gnomes.where(category: params.dig(:search, :category))
  #      else
  #        @gnomes = @gnomes.where(color: params.dig(:search, :color), category: params.dig(:search, :category))
  #      end
  #    end
  #  end

    @gnomes = policy_scope(Gnome)
    @gnomes = @gnomes.where(category: params.dig(:search, :category)) if params.dig(:search, :category) && params.dig(:search, :category) != ""
    @gnomes = @gnomes.where(color: params.dig(:search, :color)) if params.dig(:search, :color) && params.dig(:search, :color) != ""
    @gnomes = @gnomes.where(mood: params.dig(:search, :mood)) if params.dig(:search, :mood) && params.dig(:search, :mood) != ""
    @markers = @gnomes.geocoded.map do |gnome|
      {
        lat: gnome.latitude,
        lng: gnome.longitude,
        info_window: render_to_string(partial: "info_window", locals: { gnome: gnome }),
        image_url: helpers.asset_url('markergnome.png')
      }
    end
  end

  def show
    @gnome = Gnome.find(params[:id])
    authorize @gnome
    @booking = Booking.new
  end

  def new
    @gnome = Gnome.new
  end

  def my_gnomes
    authorize @gnomes
    @gnomes = Gnome.where(user: current_user)
  end

  def create
    @user = User.find(params[:user_id])
    authorize @gnomes
    @gnome = Gnome.new(gnomes_params)
    @gnome.user = @user
    @gnome.save
    redirect_to my_gnomes_gnomes_path
  end

  def edit
    @gnome = Gnome.find(params[:id])
  end

  def update
    @gnome = Gnome.find(params[:id])
    @gnome = Gnome.update(gnomes_params)
    redirect_to gnome_path(@gnome)
  end


  def destroy
    authorize @gnomes
    @gnome = Gnome.find(params[:id])
    @gnome.destroy
    redirect_to user_path
  end

    private

  def gnomes_params
    params.require(:gnome).permit(:name, :photo, :size, :weight, :state, :category, :gender, :mood, :outsider, :traveler, :available, :price, :longitude, :latitude, :color, :user_id )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = policy_scope(Review)
  end

  def new
    @gnome = Gnome.find(params[:gnome_id])
    @user = current_user
    @review = Review.new
    authorize @review
    skip_authorization
  end

  def create
    @gnome = Gnome.find(params[:gnome_id])
    @user = current_user
    @review = Review.new(reviews_params)
    authorize @review
    @review.gnome = @gnome
    @review.user = @user
    @review.save
    redirect_to gnome_path(@gnome)
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to gnome_path(@gnome)
  end

  private

  def reviews_params
    params.require(:review).permit(:comment, :rating, :gnome_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="container">
  <div class="margin-navbar card-center">
    <h1>Récapitulatif de votre réservation</h1>
    <div class="card-booking-show container">
      <div class="photo-gnome-booking" style="background-image:  url(<%= @gnome.photo %>)">
      </div>
      <h2><%= @gnome.name %></h2 >
      <% @owner = User.find(@booking.user_id) %>

      <li class="mt-3 border-bottom border-dark mb-4">
        <ul class="d-flex justify-content-between">
          <div class="first">
            <u>Propriétaire du nain :</u>
          </div>

          <div class="second">
            <strong><%= @owner.first_name %> <%= @owner.last_name %></strong>
          </div>
        </ul>

        <ul class="d-flex justify-content-between">
          <div class="first">
            <u>Date de début :</u>
          </div>

          <div class="second">
            <strong><%= @booking.date_start.day %>/<%= @booking.date_start.month %>/<%= @booking.date_start.year %></strong>
          </div>
        </ul>

        <ul class="d-flex justify-content-between">
          <div class="first">
            <u>Date de fin :</u>
          </div>

          <div class="second">
            <strong><%= @booking.date_end.day %>/<%= @booking.date_end.month %>/<%= @booking.date_end.year %></strong>
          </div>
        </ul>

        <ul class="d-flex justify-content-between">
          <div class="first">
            <u>Montant de la réservation :</u>
          </div>

          <div class="second">
            <strong><%= @booking.price_total %>€</strong>
          </div>
        </ul>
      </li>

      <div class="d-flex justify-content-between align-items-baseline">
          <div class="first">
            <%= link_to "Valider", validate_gnome_booking_path(@booking), method: :patch, class: "btn btn-ghost" %>
          </div>

          <div class="second">
            <%= link_to "Nouvelle recherche", root_path, class:"btn btn-mirror" %>
          </div>
      </div>

    </div>
  </div>
</div>

app/views/gnomes/_info_window.html.erb
<h2><%= gnome.name %></h2>
<p><%= gnome.address %></p>

app/views/gnomes/index.html.erb
<div class="container">
  <div class="margin-navbar">
      <div class="container">

        <div class="first-title mb-4"><h1>Resultats recherche</h1></div>
        <div class="mapbox" id="map"
        style="width: 115Opx; height: 400px;"data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        <div class="card-all-gnomes">
          <% @gnomes.each do |gnome|%>
            <%= link_to(gnome_path(gnome)) do %>
              <div class="card-polaroid">
                <div class="polaroid">
                  <div class="polaroid-img" style="background-image:  url(<%= gnome.photo %>)" >
                  </div>
                  <div class="caption">
                    <h3><%=  gnome.name %></h3>
                    <p><strong><%= gnome.price %></strong>€ par jour</p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/gnomes/show.html.erb
<div class="container">
  <div class="margin-navbar">
    <div id="gnome-presentation">
      <div class="card-show">
        <div class="gnome-detail">
          <%= image_tag(@gnome.photo, class:"photo-gnome") %>
          <% @gnome.reviews.each do |review| %>
            <p><%= review.comment %></p>
            <p>Note : <%= review.rating %>/5</p>
          <% end %>
        </div>
        <div class="gnome-detail">
          <h1><%= @gnome.name %></h1>
          <%= if @gnome.category == "groupé"
            render 'shared/card-gnome-groupes'
          else
            render 'shared/card-gnome-solo'
          end %>
          <%= simple_form_for [ @gnome, @booking ] do |f| %>
            <%= f.input :date_start, as: :date, html5: true, label:"Date de début" %>
            <%= f.input :date_end, as: :date, html5: true, label:"Date de fin" %>
            <div class="d-flex justify-content-between pr-5">
              <%= f.submit "Faire sa réservation", class: "btn-ghost" %>
            <% end %>
            <%= link_to "Trouver un autre gnome", root_path, class:"btn-mirror"  %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>GnomesOut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon-go.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <p class="alert"><%= alert %></p>

    <div class="content-wrapper">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
 <div class="container">
  <div id="dashboard" class="margin-navbar">
    <div class="nav nav-tabs content-dash " id="createNewTemplate" role="tablist">
      <div class="nav-item">
        <a class="tab-link active" id="Profil-tab" data-toggle="tab" data-function="Profil" href="#Profil" role="tab" aria-controls="Profil" aria-selected="true">Profil</a>
      </div>
      <div class="nav-item">
        <a class="tab-link active" id="Messages-tab" data-toggle="tab" data-function="Messages" href="#Messages" role="tab" aria-controls="Messages" aria-selected="true">Messages</a>
      </div>
      <div class="nav-item">
        <a class="tab-link" id="Réservations-tab" data-toggle="tab" href="#Réservations"data-function="Réservations" role="tab" aria-controls="Réservations" aria-selected="false">Réservations</a>
      </div>
      <div class="nav-item">
        <a class="tab-link active" id="Favoris-tab" data-toggle="tab" data-function="Favoris" href="#Favoris" role="tab" aria-controls="Favoris" aria-selected="true">Favoris</a>
      </div>
      <div class="nav-item">
        <a class="tab-link active" id="Gnomes-tab" data-toggle="tab" data-function="Gnomes" href="#Gnomes" role="tab" aria-controls="Gnomes" aria-selected="true">Gnomes</a>
      </div>
    </div>
    <div class="tab-content info-dash " id="newTemplateContent">
      <div class="tab-pane fade show active" id="Profil" role="tabpanel" aria-labelledby="Profil-tab">
       <% @user = User.find(current_user[:id]) %>
       <div class= "d-flex justify-content-arround">
          <div>
              <h2>Vos informations</h2>
              <ul id="display-info">
                <li>
                <u>Prénom : </u> <%= @user.first_name %></li>
                <li><u>Nom de famille : </u> <%= @user.last_name %></li>
                <li><u>Adresse : </u> <%= @user.address %></li>
                <li><u>Téléphone : </u> <%= @user.phone_number %></li>
                <li><u>email : </u> <%= @user.email %></li>
              </ul>
          </div>
          <div>
            <img src="https://media.vanityfair.fr/photos/60d37b70043ccb70e8d2bd2b/3:2/w_711,h_474,c_limit/vf_cover_amelie_poulain_5100.jpeg" alt="" >
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="Messages" role="tabpanel" aria-labelledby="Messages-tab">Messages content...</div>
      <div class="tab-pane list-booking fade" id="Réservations" role="tabpanel" aria-labelledby="Réservations-tab">
        <div class="card-booking-show container">
          <%@bookings.each do |booking| %>
          <div>
            <%= image_tag(booking.gnome.photo, class:"photo-recap-booking") %>
              <h2><%= booking.gnome.name %></h2>
            <ul class="d-flex justify-content-between">
              <div class="first-book">
                <u>Date de début :</u>
              </div>
              <div class="second-book">
                <strong><%= booking.date_start.day %>/<%= booking.date_start.month %>/<%= booking.date_start.year %></strong>
              </div>
            </ul>
            <ul class="d-flex justify-content-between">
              <div class="first-book">
                <u>Date de fin :</u>
              </div>
              <div class="second-book">
                <strong><%= booking.date_end.day %>/<%= booking.date_end.month %>/<%= booking.date_end.year %></strong>
              </div>
            </ul>
            <ul class="d-flex justify-content-between">
              <div class="first-book">
                <u>Propriétaire :</u>
              </div>
              <div class="second-book">
                <strong><%= booking.user.first_name %> <%= booking.user.last_name %></strong>
              </div>
            </ul>
              <h5> Réservation validée !</h3>
          </div>
          <% end %>
        </div>


      </div>
      <div class="tab-pane fade" id="Favoris" role="tabpanel" aria-labelledby="Favoris-tab">Favoris content...</div>
      <div class="tab-pane fade" id="Gnomes" role="tabpanel" aria-labelledby="Gnomes-tab"> Nous n'avez mis aucun gnome à louer.</div>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= image_path('background-gnome.jpg') %>)">
  <div class="container">
    <h1>Un vaste choix de gnomes</h1>
    <%= render 'shared/search-category' %>
  </div>
</div>

<div class="gallery">
  <%= render 'shared/card-article' %>
  <%= render 'shared/card-grid' %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="margin-navbar">
    <%= simple_form_for [ @gnome, @review ] do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating, collection: 1..5 %>
      <%= f.submit "Submit", class: "btn-ghost" %>
    <% end %>
  </div>
</div>

app/views/shared/_card-article.html.erb
<div class="card-article">

  <div class="card-article-text">
      <h2>L'impact positif des nains de jardin est prouvé</h2>
      <p>L'Institut des Etudes Gnomiques Comparées a démontré que les nains de jardin avaient un rôle bénéfique comme objet transitionnel.</p>
      <p>Le nain de jardin, souvent décrié voire moqué, en passe d’être réhabilité? Des études récentes montrent que celui-ci est bénéfique pour l’équilibre du jardin et la lutte contre les ravageurs au potager. Focus sur nos compagnons de céramique délaissés qui pourraient bien devenir un pilier du jardinage biologique. </p>
      <p>Un fait intuitivement remarqué par certains de nos anciens: les potagers ornés de nains de jardin seraient plus productifs et les légumes y seraient en meilleure santé que dans un potager sans nain. </p>
  </div>
</div>

app/views/shared/_card-gnome-groupes.erb
          <p> Salut ! Nous sommes <%= @gnome.name %>  de magnigiques nains de <%= @gnome.size.to_i %> cm et pesant <%= @gnome.weight.to_i %> grammes !
          <br>
          <%= if @gnome.outsider
                'Nous aimons aller à l\'exterieur par tout temps'
              else
                'Nous préfèrons rester au chaud à l\'intérieur. Dehors, c\'est pour les campagnards !'
              end %>
          <br>
          <%= if @gnome.traveler
                'En plus , nous voudrions voir du pays !'
              else
                'Nous sommes chauvins, nous ne voulons pas voyager!'
              end %>
          <br>
          Nous pouvons nous joindre à vous pour la somme de <%= @gnome.price.to_i %> euros par jour !

          N'hésitez pas à nous réserver, nous sommes très demandés !
          </p>

app/views/shared/_card-gnome-solo.erb
          <p> Hey! Moi, c'est <%= @gnome.name %>! Je suis
          <%= if @gnome.gender == "homme"
                'un nain'
              else
                'une naine'
              end %>
          de <%= @gnome.size.to_i %> cm et pesant <%= @gnome.weight.to_i %> grammes !
          <br>
          <%= if @gnome.outsider
                'J\'aime aller à l\'exterieur par tout temps'
              else
                'Je préfère rester au chaud à l\'intérieur. Dehors, c\'est pour les campagnards !'
              end %>
          <br>
          <%= if @gnome.traveler
                'En plus , je voudrais voir du pays !'
              else
                if @gnome.gender == "homme"
                  'Je suis chauvin, je ne veux pas voyager!'
                else
                  'Je suis chauvine, je ne veux pas voyager!'
                end
          end %>
          <br>
          Je peux me joindre à vous pour la somme de <%= @gnome.price.to_i %> euros par jour !
          <br>
          N'hésitez pas à me réserver, je suis très
          <%= if @gnome.gender == "homme"
                'demandé'
              else
                'demandée'
              end %>
          </p>

app/views/shared/_card-grid.html.erb
<div class="card-grid">
  <div class="card-polaroid">
    <div class="polaroid">
      <img src="https://i.pinimg.com/736x/25/b9/69/25b9695a5c674d6820c475cccddfb0f2--paris-eiffel-towers-tour-eiffel.jpg" alt="Gnome in front of Eiffel Tower">
      <div class="caption">
        <p>"Je n'imagine plus ma vie sans mon nain de jardin."</p>
        <h3>Anna</h3>
      </div>
    </div>
  </div>

  <div class="card-polaroid">
    <div class="polaroid">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnayT8WZiVGrSBmYA15jcK30cDWXtPq0AQePxliR5B7dswONpobc0xmfqR25BhYUSKNL0&usqp=CAU" alt="Gnome in front of a castle">
      <div class="caption">
        <p>"Mon nain de jardin m'a ouvert de nouveaux horizons.</p>
        <h3>Anne</h3>
      </div>
    </div>
  </div>

  <div class="card-polaroid">
    <div class="polaroid">
      <img src="https://images.unsplash.com/photo-1606237598791-e862e965fb9d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80" alt="Couple of gnomes">
      <div class="caption">
        <p>"Tout est plus fun avec mes nains de jardin!"</p>
        <h3>Estelle</h3>
      </div>
    </div>
  </div>

  <div class="card-polaroid">
    <div class="polaroid">
      <img src="https://images.unsplash.com/photo-1541795021-f8b60a1a456d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80" alt="Meditating Gnome">
      <div class="caption">
        <p>"Mon nain de jardin m'apporte paix et sérénité."</p>
        <h3>Mickael</h3>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github text-white"></i></a>
    <a href="#"><i class="fab fa-instagram text-white"></i></a>
    <a href="#"><i class="fab fa-facebook text-white"></i></a>
    <a href="#"><i class="fab fa-twitter text-white"></i></a>
    <a href="#"><i class="fab fa-linkedin text-white"></i></a>
  </div>
  <div class="footer-copyright">
    Gnom's out est le premier réseau de location de gnome au monde.
  </div>
</div>

app/views/shared/_search-category.html.erb
<div class="container">
  <div class="form_search">
    <%= simple_form_for :search, url: gnomes_path, method: :get do |f| %>
      <div class="questions">
        <%= f.input :category, collection: Gnome::CATEGORY, label: "Quelle categorie de gnome cherchez vous?", label_html: {class: "text-white mb-3"} %>
        <%= f.input :color, collection: Gnome::COLOR, label: "Quelle couleur de gnome cherchez vous?", label_html: {class: "text-white mb-3"} %>
        <%= f.input :mood, collection: Gnome::MOOD, label: "Quelle humeur de gnome cherchez vous?", label_html: {class: "text-white mb-3"} %>
      </div>
      <%= f.submit "Trouver votre gnome", class: "btn-ghost" %>
    <% end %>
  </div>
</div>

app/views/shared/_search-subcategory.html.erb
<div class="container">
  <div class="form_search">
    <%= simple_form_for :search, url: gnomes_path, method: :get do |f| %>
      <div class="questions">
        <%= f.input :category, collection: Gnome::CATEGORY, label: "Quelle categorie ?", label_html: {class: "$go-red mb-3"} %>
        <%= f.input :color, collection: Gnome::COLOR, label: "Quelle couleur ?", label_html: {class: "text-white mb-3"} %>
        <%= f.input :mood, collection: Gnome::MOOD, label: "Quelle humeur ?", label_html: {class: "text-white mb-3"} %>
      </div>
      <%= f.submit "Trouver votre gnome", class: "btn-mirror" %>
    <% end %>
  </div>
</div>

app/views/shared/_searchform.html.erb
<div class="container">
  <form id="searchform">
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="startdate">Date de début :</label>
        <input class="form-control string required" id="startdate" type="date" name="search[query]" id="search_query" />
      </div>
      <div class="form-group col-md-6">
        <label for="enddate">Date de fin :</label>
        <input class="form-control string required" id="enddate" type="date" name="search[query]" id="search_query" />
      </div>
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> <strong>Trouver son gnome</strong>
      </button>
    </div>
  </form>
</div>